project:
  type: website
  output-dir: docs

website:
  title: "tranrobin.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: FPCP4.qmd
        text: STAT 244-SC

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

